import { CREATURES } from '@creature-clash/battle-fixtures';
export const DEFAULT_ROSTER = [CREATURES.ASHKIT, CREATURES.FERNLET, CREATURES.VOLTIK];
export const RUN_OPPONENTS = [CREATURES.BROOKFIN, CREATURES.SLATE, CREATURES.EMBERHORN];
export const PAIRED_TEAM_A = [CREATURES.ASHKIT, CREATURES.FERNLET, CREATURES.SLATE];
export const PAIRED_TEAM_B = [CREATURES.BROOKFIN, CREATURES.VOLTIK, CREATURES.EMBERHORN];
